language: android

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "$LICENSES_HASH" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "$LICENSES_HASH_TWO" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - yes | sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-18;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-window > /dev/null 2>&1 &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./gradlew check connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "g5g+VmfqVF7PMuTl00NUQpX4pFohsEVb/SUK3adFWdT5SKOZgi28ArwUEmCMbG/he5UyyQJkv38CKfa+6jZM1cDDNkICGEjM3YCImJyCDpUKLKLFlsvDtAPK7H8rUpLgmGOHQONObtJbhtkmWg+0fr6TRj+yltZZl/6dKZ7Im4aeeMDE03Hy8MubvxRqANF3lT1bJMLUTIAP/gHSD46AKhlbnUJHW5QXqKJqMbtt3nyZNZ3aWPVMoGc+zTbpMWD6dvCH0Etc/nEatMINLunHEUf59CVEiCmQSHrWHsyDn75OiVCJUEzj9euTKE1Kz5OjKrPNYPlW1V840EOLdr/I3rz50gFmMjSyNZcd6D4W6jygOC0QDm57ISHO/Jtl4iLaPzqKMRT4daiyqWZJrnFB8Xlt8CjCxxxXT0A1ZXgro1Auoaa4OVg53Ey40CuRABHbVu6KnskcT5A52XHlDxh3wi5LnPaLH5LzB5/erFzzgLn0GPYTVKInKen6/cY+/+h84rMgS8VkKegl3oUuz1Kzej1GkxnFzdwm3j+1CuDTkadmlpn92+N6wXlG628cs7e93m0QhxXsd+mIaAwyicQeelsOeaAXTp72xfvXE7RQA2YNXjAqVoXu0kTWlXs2aDlm3HHOS4FR0kR96TJarqpinD+zAzEseaP4rMCgqdOsKok="
    - secure: "cp+/y+Zw6ijlK/JBigffDVhQyVhZTfSfgkkM5V0USlJIS2c3N7e1vruiXIcRLEIfzgTbU0veVn37NDIDMkoUDlUY9q2p0uM+xwoO8URYK/SqOhevFSd+QgMX9QwnaV5reD6aZzrz/SI6AbA6hAmIRIXZGkxRfgsB1nJN4m1Fwiwib2IXPHmBa+8d1vS7yU36FrY/3fHthgz1T1M+VDVFmbIGbBqCj5GR6CF+TcDcEQW3UvH671s7IAzuY8VzopeQjaqHE+U+8wrkg0mmiX6/B3a9nH6G/rfaeLTpomb0QCojk+W8en85f7KdK6/7SEiKU0NJmJ62ccc8n0h1VxhWYx/r2S2nVM8FfVuOTOPWuGZU0ULI1ylqAYgppBMp49eOlAJV5QzyBB7Q+py20wEPBisIlvZXLytNm7RWojiTt1wm2PaEhFzYmfPgLlViFDv7N+hLhxproDpw+c1XhhM2ZPyxW8oUriRxyMRqXkJClEgNg+0X9IyFzGc93S7yw0u5SMwhC735vjk3G4sSL/bZjre5zSc/XXM+HqIzWP+KUwRZqdcwW7uuGMB8LUWAHiCrZUuCRL25cisKW/xArH3Sg4nrFG3VP+8yMgRRVJWMtCandSzsJcBmiFPEqsb12eTo2hQfJzoKMX9HcOitfkjn1U1zsJm1ycsG61prF7fhdHg="

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
